export const datosJugadores = [
  // COLOMBIA
  { id: 1, nombre: "Camilo Vargas", equipo: "Colombia", posicion: "Arquero", foto: "/Camilo-Vargas.png", statsIA: "Camilo Vargas (Tu Titular del Minuto 1): Contra un equipo africano que presiona alto y físicamente te va a ahogar, la pegada larga de Camilo (desde el Atlas de México) es vital para saltar esa línea y habilitar directo a Luis Díaz o Jhon Durán. Va fijo en tu 11 inicial. No se cambia, suma los 90 minutos." },
  { id: 2, nombre: "Álvaro Montero", equipo: "Colombia", posicion: "Arquero", foto: "/Alvaro-Montero.png", statsIA: "Álvaro Montero (Suplente - Opción de cambio solo por Emergencia Extrema): El rival tiene delanteros potentes, pero Montero solo entraría si a Vargas lo expulsan o se lesiona. En las pollas, a menos que busques un batacazo muy raro (como una tarjeta roja al arquero), no se pone como cambio con minuto programado." },
  { id: 3, nombre: "David Ospina", equipo: "Colombia", posicion: "Arquero", foto: "/David-Ospina.png", statsIA: "David Ospina (Suplente - Líder de banco): Se queda en el banco transmitiendo calma. Tampoco es una opción real de cambio táctico por minuto para tu polla, a menos que el partido se rompa por una lesión." },
  { id: 4, nombre: "Davinson Sánchez", equipo: "Colombia", posicion: "Defensa", foto: "/Davinson-Sanchez.png", statsIA: "Davinson Sánchez (Galatasaray, Turquía) es tu titular fijo e inamovible en la zaga central para este partido contra RD Congo. Frente al biotipo físico de los africanos, que proponen duelos de pura potencia, velocidad y transiciones rápidas, Davinson es el defensor más capacitado de Colombia para jugar con metros a la espalda debido a su tremenda velocidad de recuperación y agresividad en el anticipo." },
  { id: 5, nombre: "Jhon Lucumí", equipo: "Colombia", posicion: "Defensa", foto: "/Jhon-Lucumi.png", statsIA: "Jhon Lucumí (Bologna, Italia) es el segundo central titular fijo para armar la zaga inicialista junto a Davinson Sánchez. Su presencia es fundamental contra RD Congo porque aporta el perfil zurdo, la elegancia técnica y la pausa que la defensa necesita; mientras Davinson va al choque físico y al anticipo agresivo, Lucumí es el encargado de hacer las coberturas y de dar una salida limpia y clara con el balón desde el fondo, algo clave para romper la primera línea de presión africana." },
  { id: 6, nombre: "Yerry Mina", equipo: "Colombia", posicion: "Defensa", foto: "/Yerry-Mina.png", statsIA: "Yerry Mina (Cagliari, Italia) es tu primer central suplente en el banco y una de las armas secretas más claras para tu polla en el segundo tiempo. Contra un rival físicamente desgastante como RD Congo, Mina no inicia como titular porque sufre en velocidad con los delanteros rápidos en campo abierto, pero es la pieza perfecta para ingresar en el tramo final del encuentro si las circunstancias lo requieren." },
  { id: 7, nombre: "Willer Ditta", equipo: "Colombia", posicion: "Defensa", foto: "/Willer-Ditta.png", statsIA: "Willer Ditta (Cruz Azul, México) es tu cuarto central en el orden jerárquico y, para efectos de tu polla, una pieza que se queda en el banco de suplentes sin minutos programados, a menos que ocurra una catástrofe con los titulares. Lorenzo lo lleva por su gran presente en el fútbol mexicano, pero estratégicamente sus características chocan con lo que se necesita ante RD Congo." },
  { id: 8, nombre: "Daniel Muñoz", equipo: "Colombia", posicion: "Defensa", foto: "/Daniel-Muñoz.png", statsIA: "Daniel Muñoz (Crystal Palace, Inglaterra) es tu titular indiscutible e inamovible como lateral derecho para el 11 inicial. En el contexto contra RD Congo, Muñoz es una de las piezas más importantes de la pizarra táctica de Néstor Lorenzo: al venir con el ritmo e intensidad física de la Premier League, es el único capaz de hacer toda la banda, contener los extremos rápidos de los africanos y, al mismo tiempo, ser un delantero más cuando Colombia ataca." },
  { id: 9, nombre: "Johan Mojica", equipo: "Colombia", posicion: "Defensa", foto: "/Johan-Mojica.png", statsIA: "Johan Mojica (Mallorca, España) es tu lateral izquierdo titular para enfrentar a RD Congo. En la estructura táctica de Néstor Lorenzo, el lateral izquierdo tiene una función muy específica: mientras Daniel Muñoz sube constantemente por derecha como un delantero más, Mojica es el encargado de dar amplitud por su banda, pero manteniendo un equilibrio más posicional para quedar bien parado junto a los centrales ante las transiciones veloces de los africanos." },
  { id: 10, nombre: "Santiago Arias", equipo: "Colombia", posicion: "Defensa", foto: "/Santiago-Arias.png", statsIA: "Santiago Arias (Bahia, Brasil) es tu lateral derecho suplente y una de las variantes tácticas más claras que tiene Néstor Lorenzo en el banco para la segunda mitad. A diferencia de la intensidad física y el desborde constante que ofrece Daniel Muñoz, Arias aporta un perfil de juego mucho más posicional, técnico y de control de balón, ideal para manejar los ritmos del partido según el resultado." },
  { id: 11, nombre: "Deiver Machado", equipo: "Colombia", posicion: "Defensa", foto: "/Deiver-Machado.png", statsIA: "Deiver Machado (Lens, Francia) es tu lateral izquierdo suplente, un jugador con un perfil puramente europeo, caracterizado por una intensidad física tremenda y una vocación ofensiva muy marcada. A diferencia de Mojica, que busca más el centro al área, Machado es un tractor que ataca los espacios en velocidad y rompe líneas mediante conducciones potentes, lo que lo convierte en un revulsivo ideal si el partido contra RD Congo se vuelve un ida y vuelta físico." },
  { id: 12, nombre: "Richard Ríos", equipo: "Colombia", posicion: "Mediocampista", foto: "/Richard-Rios.png", statsIA: "Richard Ríos (Palmeiras, Brasil) es tu titular indiscutible como interior derecho para el 11 inicial. En el planteamiento contra RD Congo, Ríos es el motor y el jugador que rompe los libretos: con su pasado de fútsal, tiene la pisada, la gambeta en una baldosa y el cambio de ritmo necesarios para sacarse de encima la pegajosa marca física de los africanos y generar superioridad numérica en tres cuartos de cancha." },
  { id: 13, nombre: "Jefferson Lerma", equipo: "Colombia", posicion: "Mediocampista", foto: "/Jefferson-Lerma.png", statsIA: "Jefferson Lerma (Crystal Palace, Inglaterra) es el ancla, el equilibrio y el titular indiscutible como mediocentro defensivo en tu 11 inicial. Contra RD Congo, Lerma es el jugador más importante para contener el partido: su función táctica es ser el tapón por delante de Davinson y Lucumí, encargándose de morder, raspar y ganar todos los duelos físicos en la mitad de la cancha contra los potentes volantes africanos." },
  { id: 14, nombre: "Kevin Castaño", equipo: "Colombia", posicion: "Mediocampista", foto: "/Kevin-Castaño.png", statsIA: "Kevin Castaño (Krasnodar, Rusia) es tu primer volante de marca suplente y una de las piezas de ajedrez más técnicas que tiene Néstor Lorenzo en el banco. A diferencia del despliegue físico y de choque que ofrece Lerma, Castaño es un mediocentro de posesión, pase entre líneas y distribución limpia. Ante RD Congo, es el cambio ideal para adormecer el partido mediante la circulación del balón cuando el rival esté desgastado." },
  { id: 15, nombre: "Juan Camilo Portilla", equipo: "Colombia", posicion: "Mediocampista", foto: "/Juan-Camilo-Portilla.png", statsIA: "Juan Camilo Portilla (Talleres de Córdoba, Argentina) es tu volante mixto de reserva en el banco de suplentes. Lorenzo lo lleva en la lista de 25 porque ofrece un perfil intermedio muy interesante: tiene la agresividad y el quite del fútbol argentino, pero también una gran capacidad para romper líneas conduciendo el balón hacia el frente. Sin embargo, en el orden jerárquico contra RD Congo, arranca por detrás de Ríos, Lerma y Castaño." },
  { id: 16, nombre: "Gustavo Puerta", equipo: "Colombia", posicion: "Mediocampista", foto: "/Gustavo-Puerta.png", statsIA: "Gustavo Puerta (Hull City, Inglaterra) es tu volante de reserva juvenil en el banco de suplentes. Lorenzo lo tiene muy bien conceptuado por su personalidad, su liderazgo en las juveniles y su capacidad para acoplarse al ritmo europeo, pero en la jerarquía actual de la Selección absoluta frente a un rival del corte de RD Congo, se ubica como la última opción de recambio en la zona de volantes." },
  { id: 17, nombre: "Jhon Arias", equipo: "Colombia", posicion: "Mediocampista", foto: "/Jhon-Arias.png", statsIA: "Jhon Arias (Fluminense, Brasil) es tu titular indiscutible por la banda derecha (o como extremo interiorizado) en el 11 inicial. Para el cuerpo técnico, Arias es el jugador tácticamente más inteligente, equilibrado y obediente de todo el frente de ataque. Contra la potencia física de RD Congo, su rol es vital: es el socio que le cuida la espalda a James Rodríguez, el que se asocia a un toque con Daniel Muñoz y el primero en presionar la salida rival." },
  { id: 18, nombre: "Jorge Carrascal", equipo: "Colombia", posicion: "Mediocampista", foto: "/Jorge-Carrascal.png", statsIA: "Jorge Carrascal (Dinamo Moscú, Rusia) es tu principal revulsivo de talento y el Plan A desde el banco para cambiarle la cara al partido en el segundo tiempo. Contra el bloque físico y denso de RD Congo, Carrascal no inicia como titular porque Lorenzo prefiere el orden táctico de Jhon Arias y la jerarquía de James Rodríguez, pero su capacidad para encarar, romper líneas en conducción y filtrar pases entre líneas lo convierte en el jugador ideal para romper la defensa africana cuando empiece a aparecer el cansancio." },
  { id: 19, nombre: "Juan Fernando Quintero", equipo: "Colombia", posicion: "Mediocampista", foto: "/Juan-Fernando-Quintero.png", statsIA: "Juan Fernando Quintero (Racing Club, Argentina) es tu segundo organizador en el banco de suplentes y una pieza de lujo absoluto para el manejo de los tiempos. Contra un rival como RD Congo, Juanfer representa la pausa, la claridad mental y la precisión quirúrgica. No arranca como titular porque Lorenzo prefiere la intensidad física de Arias y la jerarquía de James, pero Quintero es el jugador ideal para cambiar el ritmo del partido a través del pase y la pelota quieta cuando el rival deje espacios por el cansancio." },
  { id: 20, nombre: "James Rodríguez", equipo: "Colombia", posicion: "Mediocampista", foto: "/James-Rodriguez.png", statsIA: "James Rodríguez (Rayo Vallecano, España) es el capitán, el líder futbolístico y el titular inamovible como enganche en tu 11 inicial. Para Néstor Lorenzo, James es el alma del equipo y el director de la orquesta. Contra el orden defensivo y la fuerza de RD Congo, su visión de juego es el recurso principal para desactivar el plano físico del rival: si el partido se juega a correr, Colombia sufre; si el partido se juega al ritmo de James, Colombia domina." },
  { id: 21, nombre: "Jáminton Campaz", equipo: "Colombia", posicion: "Mediocampista", foto: "/Jaminton-Campaz.png", statsIA: "Jáminton Campaz (Rosario Central, Argentina) es tu extremo izquierdo de reserva en el banco de suplentes. Campaz aporta un perfil muy específico de aceleración, enganche hacia adentro y un remate de media distancia sumamente potente con su pierna zurda. Sin embargo, en la planificación de Néstor Lorenzo contra RD Congo, el bicho de Rosario arranca bastante atrás en la rotación de los extremos, superado por la jerarquía de Luis Díaz." },
  { id: 22, nombre: "Juan Camilo Hernández", equipo: "Colombia", posicion: "Delantero", foto: "/Juan-Camilo-Hernandez.png", statsIA: "Juan Camilo 'Cucho' Hernández (Columbus Crew, EE. UU.) es tu delantero centro móvil y extremo polifuncional de reserva en el banco. El Cucho te ofrece un perfil ofensivo espectacular y moderno: no es el típico '9' de área que se queda esperando el balón, sino un atacante con muchísima movilidad, potencia física, un remate de media distancia letal y la capacidad de caer a jugar por cualquiera de las dos bandas. Sin embargo, en el orden de prioridades de Néstor Lorenzo contra RD Congo, arranca por detrás de los delanteros centro definidos y los extremos principales." },
  { id: 23, nombre: "Luis Díaz", equipo: "Colombia", posicion: "Delantero", foto: "/luis-diaz.png", statsIA: "Luis Diaz (Liverpool, Inglaterra) es la máxima estrella, el jugador más desequilibrante y el titular inamovible como extremo izquierdo en tu 11 inicial. Contra RD Congo, Lucho es la principal arma de destrucción masiva que tiene Colombia: su capacidad para encarar en el uno contra uno, su velocidad de élite y sus diagonales hacia el área van a obligar a la defensa africana a replegarse y a escalonar marcas, lo que liberará espacios para James Rodríguez y el delantero centro." },
  { id: 24, nombre: "Luis Suárez", equipo: "Colombia", posicion: "Delantero", foto: "/Luis-Suarez.png", statsIA: "Luis Suárez (Almería, España) es tu delantero centro de potencia y alternativa de choque en el banco de suplentes. El atacante de la liga española te ofrece un perfil puramente físico: es un '9' con una fuerza descomunal para pelear de espaldas, chocar con los centrales y picar al espacio con mucha potencia. Contra el biotipo de RD Congo, Suárez es un perfil muy útil porque no se va a dejar amedrentar por el rigor físico de los defensores africanos. Sin embargo, en el orden de Néstor Lorenzo, arranca por detrás de Jhon Durán y Rafael Santos Borré." },
  { id: 25, nombre: "Carlos Andrés Gómez", equipo: "Colombia", posicion: "Delantero", foto: "/Carlos-Andres-Gomez.png", statsIA: "Carlos Andrés Gómez (Rennes, Francia) es tu extremo derecho revulsivo de pura velocidad en el banco de suplentes. El ex-Millonarios te ofrece su perfil: es un extremo derecho natural, picante, que busca el duelo individual en velocidad y el desborde hasta la línea de fondo para asistir al '9'. Contra un rival desgastado como RD Congo, sus piernas frescas y su aceleración pueden hacer estragos, aunque en la consideración inicial de Lorenzo arranca por detrás de la jerarquía de Jhon Arias y la experiencia de Luis Sinisterra." },
  { id: 26, nombre: "Jhon Córdoba", equipo: "Colombia", posicion: "Delantero", foto: "/Jhon-Cordoba.png", statsIA: "Jhon Córdoba (Krasnodar, Rusia) disputa palmo a palmo el puesto de delantero centro titular en tu 11 inicial. Para Néstor Lorenzo, Córdoba es el tanque ideal cuando se necesita un '9' de tremenda potencia física, capaz de chocar contra defensores corpulentos, aguantar el balón de espaldas y arrastrar marcas para liberar a los extremos. Contra el biotipo rústico de RD Congo, su carrocería y oficio en el área son argumentos letales." },
  
  // RD CONGO
  { id: 27, nombre: "Timothy Fayulu ", equipo: "RD Congo", posicion: "Arquero", foto: "/Timothy-Fayulu.png", statsIA: "Timothy Fayulu (Sion, Suiza) es el arquero suplente de la Selección de la República Democrática del Congo. Aunque viene teniendo un rendimiento muy destacado y regular en el fútbol suizo, en el orden jerárquico de los Leopardos arranca por detrás del consolidado Lionel Mpasi (el héroe de la última Copa Africana) o de la experiencia de Dimitry Bertaud." },
  { id: 28, nombre: "Lionel Mpasi ", equipo: "RD Congo", posicion: "Arquero", foto: "/Lionel-Mpasi.png", statsIA: "Lionel Mpasi (Rodez AF, Francia) es el arquero titular indiscutible y una de las grandes figuras de la Selección de la República Democrática del Congo. Se consolidó como un héroe nacional en su país tras su impresionante actuación en la Copa Africana de Naciones, donde no solo atajó penales clave, sino que incluso anotó el penal decisivo en una tanda histórica frente a Egipto. Es el dueño absoluto del arco de los Leopardos." },
  { id: 29, nombre: "Matthieu Epolo", equipo: "RD Congo", posicion: "Arquero", foto: "/Matthieu-Epolo.png", statsIA: "Matthieu Epolo (Standard de Lieja, Bélgica) es el tercer arquero o guardameta de proyección en la Selección de la República Democrática del Congo. A pesar de su enorme proyección y de estar ganando un roce importante en el fútbol belga a su corta edad, en la consideración del técnico Sébastien Desabre se ubica en el último escalón de la rotación de porteros, por detrás de Lionel Mpasi y de los suplentes inmediatos." },
  { id: 30, nombre: "Aaron Wan-Bissaka", equipo: "RD Congo", posicion: "Defensa", foto: "/Aaron-Wan.png", statsIA: "Aaron Wan-Bissaka (West Ham United, Inglaterra) es el lateral derecho titular indiscutible y una de las murallas defensivas más imponentes de la Selección de la República Democrática del Congo. Su decisión de representar a los Leopardos le da un salto de calidad élite a la zaga africana; al ser uno de los mejores defensores del mundo en el uno contra uno en la Premier League, su duelo individual contra Luis Díaz será el choque más espectacular y táctico de todo el partido." },
  { id: 31, nombre: "Gédéon Kalulu", equipo: "RD Congo", posicion: "Defensa", foto: "/Gédéon-Kalulu.png", statsIA: "Aaron Wan-Bissaka (West Ham United, Inglaterra) es el lateral derecho titular indiscutible y una de las murallas defensivas más imponentes de la Selección de la República Democrática del Congo. Su decisión de representar a los Leopardos le da un salto de calidad élite a la zaga africana; al ser uno de los mejores defensores del mundo en el uno contra uno en la Premier League, su duelo individual contra Luis Díaz será el choque más espectacular y táctico de todo el partido." },
  { id: 32, nombre: "Joris Kayembe", equipo: "RD Congo", posicion: "Defensa", foto: "/Joris-Kayembe.png", statsIA: "Joris Kayembe (KRC Genk, Bélgica) es el lateral izquierdo titular o en disputa directa por el puesto en la Selección de la República Democrática del Congo. El jugador del fútbol belga te ofrece una salida limpia, potencia física y un despliegue constante por la banda izquierda de los Leopardos, siendo una pieza de mucha confianza para el técnico Sébastien Desabre por su experiencia en Europa." },
  { id: 33, nombre: "Arthur Masuaku ", equipo: "RD Congo", posicion: "Defensa", foto: "/Arthur-Masuaku.png", statsIA: "Arthur Masuaku (Beşiktaş, Turquía) es el lateral izquierdo experimentado y el gran especialista de la pelota quieta en la Selección de la República Democrática del Congo. Masuaku sostiene una disputa espectacular posición por posición con Joris Kayembe. Mientras Kayembe aporta un perfil más defensivo y de despliegue físico, Masuaku es pura técnica: tiene una proyección al ataque magnífica, un centro impecable y un guante en su pierna zurda para cobrar tiros libres y saques de esquina." },
  { id: 34, nombre: "Steve Kapuadi", equipo: "RD Congo", posicion: "Defensa", foto: "/Steve-Kapuadi.png", statsIA: "Steve Kapuadi (Legia de Varsovia, Polonia) es un defensor central de reserva en la Selección de la República Democrática del Congo. Con su imponente 1.96 metros de estatura, el zaguero del fútbol polaco le ofrece al técnico Sébastien Desabre una alternativa de pura altura, fortaleza en los duelos individuales y un perfil zurdo natural para la zaga. Sin embargo, en el orden jerárquico de los Leopardos, arranca por detrás de la consolidada pareja titular de Chancel Mbemba y Dylan Batubinsika." },
  { id: 35, nombre: "Rocky Bushiri", equipo: "RD Congo", posicion: "Defensa", foto: "/Rocky-Bushiri.png", statsIA: "Rocky Bushiri (Hibernian, Escocia) es un defensor central de reserva y de corte netamente físico en la Selección de la República Democrática del Congo. Con su imponente carrocería y su formación en el fútbol británico, Bushiri es el típico zaguero de choque, fuerte en el contacto y muy agresivo en la marca hombre a hombre. Sin embargo, en la pizarra del técnico Sébastien Desabre, arranca la rotación por detrás de los titulares inamovibles (Chancel Mbemba y Dylan Batubinsika) e incluso de las primeras alternativas de perfil zurdo." },
  { id: 36, nombre: "Axel Tuanzebe", equipo: "RD Congo", posicion: "Defensa", foto: "/Axel-Tuanzebe.png", statsIA: "Axel Tuanzebe (Ipswich Town, Inglaterra) es el defensor central o lateral derecho de jerarquía y polifuncionalidad en la Selección de la República Democrática del Congo. Su pasado en el Manchester United y su gran presente en el fútbol inglés le dan un estatus de jugador de élite dentro del plantel. En la pizarra del técnico Sébastien Desabre, Tuanzebe te ofrece una flexibilidad táctica tremenda: puede jugar como central (su posición natural) para armar una línea de tres, o plantarse como un lateral derecho sumamente fuerte y de corte defensivo." },
  { id: 37, nombre: "Chancel Mbemba ", equipo: "RD Congo", posicion: "Defensa", foto: "/Chancel-Mbemba.png", statsIA: "Chancel Mbemba (Olympique de Marsella, Francia) es el gran mariscal, capitán indiscutible y el líder absoluto de la Selección de la República Democrática del Congo. Es la pieza más importante de toda la estructura defensiva de los Leopardos. Su jerarquía en el fútbol europeo y su imponente físico lo convierten en el verdadero termómetro de la resistencia africana; el duelo que sostenga en el área contra el '9' de Colombia (sea Jhon Córdoba o Jhon Durán) será una batalla de titanes." },
  { id: 38, nombre: "Dylan Batubinsika ", equipo: "RD Congo", posicion: "Defensa", foto: "/Dylan-Batubinsika.png", statsIA: "Dylan Batubinsika (Saint-Étienne, Francia) es el defensor central titular y el socio de confianza del capitán Chancel Mbemba en la zaga de la Selección de la República Democrática del Congo. El zaguero del fútbol francés aporta el perfil de guardaespaldas: es un central tiempista, muy seguro en los relevos, con un físico imponente y una gran capacidad para el anticipo terrestre y aéreo." },
  { id: 39, nombre: "Noah Sadiki", equipo: "RD Congo", posicion: "Mediocampista", foto: "/Noah-Sadiki.png", statsIA: "Noah Sadiki (Union Saint-Gilloise, Bélgica) es la joya joven del mediocampo y el revulsivo táctico de la Selección de la República Democrática del Congo. Con apenas 21 años, el volante nacido en Bruselas aporta una dinámica moderna impresionante: es un jugador polivalente de ida y vuelta (box-to-box), con excelente primer pase, técnica limpia para salir jugando de espaldas y una gran intensidad para presionar." },
  { id: 40, nombre: "Samuel Moutoussamy ", equipo: "RD Congo", posicion: "Mediocampista", foto: "/Samuel-Moutoussamy.png", statsIA: "Samuel Moutoussamy (Sivasspor, Turquía) es el motor, el equilibrio y el volante de marca titular en la Selección de la República Democrática del Congo. Es el jugador de confianza del técnico Sébastien Desabre para morder en la mitad de la cancha, hacer el trabajo sucio y mantener el orden táctico. Su misión principal en este partido será gigantesca: convertirse en la sombra de James Rodríguez para cortar los hilos del juego colombiano." },
  { id: 41, nombre: "Edo Kayembe", equipo: "RD Congo", posicion: "Mediocampista", foto: "/Edo-Kayembe.png", statsIA: "Edo Kayembe (Watford, Inglaterra) es el volante central titular de jerarquía y juego mixto en la Selección de la República Democrática del Congo. A diferencia de otros mediocampistas de corte puramente destructivo, el jugador del Watford inglés le aporta a los Leopardos el equilibrio perfecto entre la fuerza física de la Championship y una gran claridad técnica para distribuir la pelota, armar la salida y rematar de media distancia con su potente pierna zurda." },
  { id: 42, nombre: "Ngal'ayel Mukau", equipo: "RD Congo", posicion: "Mediocampista", foto: "/Ngal'ayel-Mukau.png", statsIA: "Ngal'ayel Mukau (Lille, Francia) es una de las joyas emergentes y volantes de proyección más cotizados en la Selección de la República Democrática del Congo. Con su reciente salto al fútbol de élite francés, el joven mediocentro de 21 años aporta un perfil moderno de pivote: es largo, técnico, rompe líneas con pases verticales y tiene una zancada espectacular para recuperar balones." },
  { id: 43, nombre: "Charles Pickel", equipo: "RD Congo", posicion: "Mediocampista", foto: "/Charles-Pickel.png", statsIA: "Charles Pickel (Cremonese, Italia) es el volante mixto por excelencia, el perro de caza y titular indiscutible en el mediocampo de la Selección de la República Democrática del Congo. El jugador formado en Suiza le aporta a los Leopardos todo el rigor táctico, la disciplina y la intensidad física del fútbol italiano. Es un especialista en el juego de presión alta, romper líneas enemigas a pura potencia y llegar por sorpresa al área rival desde la segunda línea (perfil box-to-box)." },
  { id: 44, nombre: "Nathanael Mbuku", equipo: "RD Congo", posicion: "Mediocampista", foto: "/Nathanael-Mbuku.png", statsIA: "Nathanael Mbuku (Dinamo Zagreb, Croacia / ex-Augsburgo) es el extremo por derecha revulsivo y la carta de desequilibrio rápido en el frente de ataque de la Selección de la República Democrática del Congo. Tras hacer todo su proceso formativo en las juveniles de Francia, el habilidoso extremo zurdo optó por representar a los Leopardos, aportando esa escuela europea de juego asociado, velocidad punzante con perfil cambiado y un enganche hacia adentro sumamente peligroso." },
  { id: 45, nombre: "Brian Cipenga", equipo: "RD Congo", posicion: "Mediocampista", foto: "/Brian-Cipenga.png", statsIA: "Brian Cipenga (PAOK, Grecia) es un extremo izquierdo de reserva en la Selección de la República Democrática del Congo. Es un jugador desequilibrante, rápido y con muy buen regate en el uno contra uno; sin embargo, en la estricta jerarquía de los Leopardos, tiene por delante a figuras consolidadas en las ligas top de Europa como Yoane Wissa (Brentford) o Silas Katompa Mvumpa. Por esta razón, su rol principal es el de una alternativa profunda en el banco de suplentes." },
  { id: 46, nombre: "Théo Bongonda", equipo: "RD Congo", posicion: "Mediocampista", foto: "/Théo-Bongonda.png", statsIA: "Théo Bongonda (Spartak de Moscú, Rusia) es el extremo derecho titular, el mago de la gambeta y el principal generador de peligro en el ataque de la Selección de la República Democrática del Congo. Con su clásico perfil cambiado (es zurdo pero juega por la banda derecha), Bongonda es el encargado de inventar las jugadas individuales, desequilibrar en el mano a mano y buscar diagonales venenosas hacia el centro. Su duelo individual contra Johan Mojica será uno de los puntos más calientes del partido." },
  { id: 47, nombre: "Gaël Kakuta", equipo: "RD Congo", posicion: "Mediocampista", foto: "/Gaël-Kakuta.png", statsIA: "Gaël Kakuta (Amiens, Francia / ex-Chelsea y Sevilla) es el cerebro, el veterano de mil batallas y el dueño de la magia en la Selección de la República Democrática del Congo. A sus 34 años, el talentoso mediapunta zurdo representa la pausa, la visión de juego periférica y la calidad técnica diferencial de los Leopardos. Aunque los años le han restado el despliegue físico de su juventud, su capacidad para filtrar pases quirúrgicos entrelíneas y su maestría en la ejecución de la pelota quieta lo mantienen como el 10 natural del equipo." },
  { id: 48, nombre: "Meschack Elia", equipo: "RD Congo", posicion: "Delantero", foto: "/Meschack-Elia.png", statsIA: "Meschack Elia (Young Boys, Suiza) es la flecha, el velocista y el jugador más impredecible en el ataque de la Selección de la República Democrática del Congo. Con una aceleración brutal y un cambio de ritmo letal, Elia es el especialista de los Leopardos para destrozar defensas de contragolpe. Su gran ventaja es la versatilidad: puede jugar como extremo por izquierda (haciendo la diagonal hacia adentro), por derecha, o incluso como un segundo delantero suelto para presionar la salida de los centrales." },
  { id: 49, nombre: "Fiston Mayele", equipo: "RD Congo", posicion: "Delantero", foto: "/Fiston-Mayele.png", statsIA: "Fiston Mayele (Pyramids FC, Egipto) es el delantero centro de área, definidor puro y el revulsivo de gol en la Selección de la República Democrática del Congo. Conocido por su tremendo olfato goleador y sus movimientos de depredador dentro del área, Mayele es un '9' clásico: potente, muy fuerte en el juego aéreo y letal cuando le queda un balón suelto frente al arco." },
  { id: 50, nombre: "Cédric Bakambu", equipo: "RD Congo", posicion: "Delantero", foto: "/Cédric-Bakambu.png", statsIA: "Cédric Bakambu (Real Betis, España) es el máximo referente histórico en ataque, el goleador de raza y el gran líder ofensivo de la Selección de la República Democrática del Congo. Con 34 años, Bakagoal aporta una jerarquía internacional inigualable para los Leopardos: su tremenda velocidad en distancias cortas, sus desmarques de ruptura al espacio y su frialdad letal de cara al arco lo convierten en el delantero más temido del plantel africano. El duelo táctico y físico que sostendrá contra Dávinson Sánchez sacará chispas." },
  { id: 51, nombre: "Simon Banza", equipo: "RD Congo", posicion: "Delantero", foto: "/Simon-Banza.png", statsIA: "Simon Banza (Trabzonspor, Turquía / ex-Braga) es el delantero centro de potencia, juego asociativo y gran envergadura de la Selección de la República Democrática del Congo. Con su impresionante planta física (casi 1.90 m), Banza le ofrece a los Leopardos un registro de ataque completamente distinto al de Cédric Bakambu: es el típico 9 de apoyo, extraordinario para jugar de espaldas, aguantar los balones largos, habilitar a los extremos rápidos (como Wissa o Bongonda) y dominar el juego aéreo en ambas áreas." },
  { id: 51, nombre: "Yoane Wissa", equipo: "RD Congo", posicion: "Delantero", foto: "/Yoane-Wissa.png", statsIA: "Yoane Wissa (Brentford, Inglaterra) es la máxima estrella, el jugador más desequilibrante de la Premier League y el alma ofensiva de la Selección de la República Democrática del Congo. Wissa representa la máxima amenaza para Colombia: un atacante ultra veloz, con un regate impredecible en carrera, astuto para atacar los espacios y con una frialdad de cara al gol pulida en el fútbol inglés." }

];

export const analisisPartidoIA = {
  titulo: "Análisis General de la Inteligencia Artificial",
  resumen: "Colombia llega con un invicto histórico impresionante bajo el mando de Néstor Lorenzo, mostrando un juego ofensivo demoledor y alta cohesión táctica. Por su parte, la República Democrática del Congo (los 'Leopardos') es una de las selecciones más físicas, ordenadas y peligrosas de África, especialista en transiciones rápidas y en complicar a equipos grandes.",
  datosClave: [
    "Tendencia de Colombia: Suele anotar en el 85% de sus partidos recientes. Su marcador más repetido es el 2-1 o 2-0.",
    "Tendencia de RD Congo: Recibe muy pocos goles por partido debido a su bloque defensivo bajo. Sus partidos suelen ser cerrados (1-0 o 1-1).",
    "Pronóstico Inteligente: Un marcador muy probable si quieres arriesgar es un 2-1 a favor de Colombia, o un 1-1 si los africanos logran cerrar los espacios temprano."
  ]
};